version: '3.8'

services:
  app:
    # build:
    #   context: .
    #  dockerfile: .docker/Dockerfile
    image: sherwinowen/laravel-agg:1.0
    container_name: laravel_app
    #volumes:
    #  - ./app:/var/www/html
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:

