# k8s/laravel-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: laravel
spec:
  replicas: 1
  selector:
    matchLabels:
      app: laravel
  template:
    metadata:
      labels:
        app: laravel
    spec:
      containers:
      - name: laravel
        image: us-central1-docker.pkg.dev/dev-staging-337304/laravel-repo/laravel-app:v3
        ports:
          - containerPort: 80
        env:
          - name: APP_ENV
            value: production
          - name: APP_DEBUG
            value: "true"
          - name: LOG_CHANNEL
            value: stderr
          - name: DB_CONNECTION
            value: mysql
          - name: DB_HOST
            value: mysql
          - name: DB_PORT
            value: "3306"
          - name: DB_DATABASE
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_DATABASE
          - name: DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: MYSQL_PASSWORD
---
# k8s/laravel-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: laravel
spec:
  type: LoadBalancer
  selector:
    app: laravel
  ports:
    - port: 80
      targetPort: 80
